### ISSUE TITLE
그룹 삭제 시 유저가 속한 그룹에 해당 그룹이 남아요

### ISSUE THREAD

**Issue by limsubinn** [Relay-UMC23/relay-server#112]
clubIdx 46을 삭제했는데 그룹 목록에는 해당 그룹이 삭제되지만, 
유저(userIdx 6)가 속한 그룹에는 해당 그룹이 남아있어서 오류가 발생합니다!

**Comment by Yeonji-Lim** [comment]
이부분 issue 99와 함께 해결하겠습니다.

**Comment by Yeonji-Lim** [comment]
#99 로 해결되어 이슈 닫겠습니다~
