### ISSUE TITLE
그룹 목록이 조회 안되고 있습니다

### ISSUE THREAD

**Issue by Yeonji-Lim** [Relay-UMC23/relay-server#113]
검색어 없이 그룹 목록 조회시 조회가 안되고 데이터베이스 에러뜨고 있어요

**Comment by dasomahn** [comment]
이 이슈 서버db 말고 로컬 db에서도 그래서 저도 저녁쯤 한번 확인해보겠습니다!!

**Comment by Yeonji-Lim** [comment]
우선 서버db 상에 문제되는 그룹의 status를 inactive 처리하여 배포된 서버 상에서는 해결하였습니다.
제가 발견한 특이점은 해당 그룹의 방장이 memberstatus가 없다는 점입니당
이 이슈는 솜 확인 후 해결되면 닫겠습니다~

**Comment by dasomahn** [comment]
저의 경우는 한 프로필이 여러개 그룹의 host여서 생겼던 문제 같습니다! 저도 우선 프로필 하나당 한 그룹만 active로 남기고 다른 그룹들은 inactive로 바꾸니 해결되었습니다~!
