### ISSUE TITLE
그룹 생성 API를 `/clubs`으로 POST 보내는 것으로 바꾸는 거 어떨까요?

### ISSUE THREAD

**Issue by Yeonji-Lim** [Relay-UMC23/relay-server#68]
현재는 `clubs/apply/{userProfileIdx}/generates`에 요청하고 있는데, 

principal 받는 걸로 하면 프로필 아이디도 필요없어서 `/clubs`로 POST하는 방식이 어떤가 싶어요!

현재 이 위치로 POST하는게 없어요

**Comment by lueahc** [comment]
저는 좋아요. 그리고 ClubController로 이동하는 건 어떤가요? 그룹 생성 뿐만 아니라 MemberStatusController에 있는 그룹 전체 시간표 조회도 ClubController에 넣는 건 어떤가 싶어요.

**Comment by dasomahn** [comment]
> principal 받는 걸로 하면 프로필 아이디도 필요없어서 `/clubs`로 POST하는 방식이 어떤가 싶어요!

근데 principal로는 유저만 받고 프로필 정보는 특정 못하니까
일부러 프로필 인덱스 받아오는 방식으로 한거 아니었나용? (대신 principal로 넘긴 유저의 프로필인지는 검증)
URI 조금 짧게 줄이는 건 찬성이에요!

**Comment by Yeonji-Lim** [comment]
> 저는 좋아요. 그리고 ClubController로 이동하는 건 어떤가요? 그룹 생성 뿐만 아니라 MemberStatusController에 있는 그룹 전체 시간표 조회도 ClubController에 넣는 건 어떤가 싶어요.

그렇게 진행하는걸로 할게용

> 근데 principal로는 유저만 받고 프로필 정보는 특정 못하니까 일부러 프로필 인덱스 받아오는 방식으로 한거 아니었나용? (대신 principal로 넘긴 유저의 프로필인지는 검증)

아 맞네요! 그룹 생성전이라서 클럽의 프로필이랑 대조를 못하는 군요;; 그룹삭제 로직이랑 혼동왔네요

현재 프로필을 body로 받게 하는거 어떨까요?

**Comment by Yeonji-Lim** [comment]
#78 로 해결되어 이슈 닫습니다
