### ISSUE TITLE
기록 조회 부분에 목표 추가해주세요!

### ISSUE THREAD

**Issue by limsubinn** [Relay-UMC23/relay-server#70]
목표 기준, 목표 값 추가 부탁드립니다..!

**Comment by dasomahn** [comment]
@limsubinn 기록 idx로 조회하는 /record/{idx} API 말씀이신거죠? 추가하겠습니다!

**Comment by Yeonji-Lim** [comment]
기록을 조회하는 모든 API에 포함되어야 합니다!
