### ISSUE TITLE
기록 조회 부분 평균페이스 NaN 값일 때 0으로 처리해주세요!

### ISSUE THREAD

**Issue by limsubinn** [Relay-UMC23/relay-server#71]
NaN 값을 안드로이드에서 처리할 수가 없어서 바로 onFailure 메소드로 넘어가고 있어요

**Comment by Yeonji-Lim** [comment]
이부분 일단 개인 일별 요약에서 발생하는 거 확인했다고 합니다!

**Comment by dasomahn** [comment]
@limsubinn 
우선 수정해놓겠습니다 리페 감사해요 🥰

근데 궁금한게 두 부분 있습니다!
1. 페이스가 NaN이 되는 건 어떤 경우인가요?
달리기를 종료할 때 서버에 오는 값 중 pace가 NaN형태로 넘겨지는 건가요?

2. 개인 일별 요약API는 어떤 기능에서 사용되나요?
사실 이 API는 당장 사용되는 용도가 아닌..걸로 만들었어서요!
이 이슈 해결되기 전까지
캘린더 작성할때 /record/summary로 해당 월 기록 가져오고
세부 기록페이지는 위에서 recordIdx로 /record/{idx} 조회한거로 처리하고계심 될 것 같아요!

**Comment by Yeonji-Lim** [comment]
> 1. 페이스가 NaN이 되는 건 어떤 경우인가요?
>    달리기를 종료할 때 서버에 오는 값 중 pace가 NaN형태로 넘겨지는 건가요?

제가 보니까 달리기 시작/종료와 관계 없이 일별 요약을 요청했을 때 기록이 없으면 속도 연산에서 기록 개수인 0 으로 나눠버려서 NaN형태로 가는거더라구요 서버에 오는 값과는 상관없습니다!

**Comment by dasomahn** [comment]
> 제가 보니까 달리기 시작/종료와 관계 없이 일별 요약을 요청했을 때 기록이 없으면 속도 연산에서 기록 개수인 0 으로 나눠버려서 NaN형태로 가는거더라구요 서버에 오는 값과는 상관없습니다!

아 그런거군요! 확인했습니다 감사합니다 👍🏻

**Comment by Yeonji-Lim** [comment]
> 2. 개인 일별 요약API는 어떤 기능에서 사용되나요?
>    사실 이 API는 당장 사용되는 용도가 아닌..걸로 만들었어서요!
>    이 이슈 해결되기 전까지
>    캘린더 작성할때 /record/summary로 해당 월 기록 가져오고
>    세부 기록페이지는 위에서 recordIdx로 /record/{idx} 조회한거로 처리하고계심 될 것 같아요!

이 부분은 사실 맞긴하네요 프로필이 여러개인 경우에 해당하는 API 인거 같아서.. 

그런데 월별 기록에서 특정 날짜를 누르면 그 날짜에 해당하는 기록의 인덱스를 가지고 요청하는 거보다 
날짜를 요청하고 기록을 보여주는 게 낫지 않을까요?

**Comment by dasomahn** [comment]
> 그런데 월별 기록에서 특정 날짜를 누르면 그 날짜에 해당하는 기록의 인덱스를 가지고 요청하는 거보다
> 날짜를 요청하고 기록을 보여주는 게 낫지 않을까요?

이거는 리페가 따로 API 만들어주지 않았나요?!

**Comment by Yeonji-Lim** [comment]
아 그거 제가 만든게 아니라 만든 거를 수정했어요..! 저는 솜이 만드신 줄 알았는데; 😂
일단 이부분은 해결되었으니 닫겠습니다! #73
