### ISSUE TITLE
한 프로필 당 하나의 그룹에만 참여할 수 있도록 변경해주세요

### ISSUE THREAD

**Issue by Yeonji-Lim** [Relay-UMC23/relay-server#85]
현재는 하나의 프로필이 여러개의 그룹에 들어갈 수 있어요

**Comment by lueahc** [comment]
`DUPLICATE_MEMBER_STATUS`로 걸러내고 있는데 안 걸러지나요?

**Comment by dasomahn** [comment]
> `DUPLICATE_MEMBER_STATUS`로 걸러내고 있는데 안 걸러지나요?

처리가 되어있긴 한데 active한지만 걸러서 accepted 인 상태 검증도 추가해야할 것 같고,
exception들이 catch에서 안잡히는 상태라 제가 issue#75랑 묶어서 이것저것 수정하고 pr 올리겠습니다!
