### ISSUE TITLE
하루에 한번만 뛸 수 있나요?

### ISSUE THREAD

**Issue by dasomahn** [Relay-UMC23/relay-server#94]
시간표는 하루에 한 블록만 등록되게 구현된거로 알고 있습니다.
근데 그러면 해당 시간 내에 시작하고 멈추고 또 시작할 수 있는건가요?
ex) 시간표 등록 10:00 ~ 12:00
10:30 시작 11:00 종료
11:30 시작 12:00 종료

현재는 요거에 대한 별다른 제한이 없어서 시간표만 맞다면 하루에 여러번 기록할 수 있고,
그 상태에서 데일리 기록 조회 시 오류가 발생합니다

이 부분에 대한 논의는 없긴 했는데, 저는 암묵적으로 안된다고 생각했거든요
저런거를 방지해서 일시정지 기능이 있기도 하고... 
만약 이 제한을 적용시킨다면, **달리기 시작 시 오늘 이미 달렸는지 확인**하는 과정이 빠르게 필요할 것 같습니다! @shortboy7 
(프론트에서는 모르시는건지 하루에 막 여러개씩 등록해놓으시더라구요 ㅠ)
데일리 기록 조회쪽도 더블체킹해서 두개있을 경우 오류 뱉도록 수정하겠습니다!

**Comment by Yeonji-Lim** [comment]
이 부분 지난 번에 프론트에서 오늘 기록 조회가 안된다는 그부분일까요??

**Comment by dasomahn** [comment]
> 이 부분 지난 번에 프론트에서 오늘 기록 조회가 안된다는 그부분일까요??

맞아요 하루에 한 기록만 있다는 가정하에 짜놔서...
하루에 두번 이상 뛰면 서버 에러 떠요 그 부분은 아직 예외처리 안해놔거든요 😓

**Comment by shortboy7** [comment]
이 부분 작업해서 올리겠습니다.

**Comment by Yeonji-Lim** [comment]
하루에 한번 뛰는 것으로 제한하고 서버에서 예외처리 해주는 것으로 진행하겠습니다!

**Comment by Yeonji-Lim** [comment]
아 그런데,, 그렇게 제한해두면 시연할 때 한번 밖에 못보여 주지 않나요...?
유저 입장에서도 하루에 한 기록이 이어지는 편이 좋을 거 같기도 하고요 

그 시간 내의 모든 기록을 가져오는 것은 무리일까요

**Comment by shortboy7** [comment]
오전에 뛰고 오후에 뛰고 이런 것도 안되는 건가요?

**Comment by Yeonji-Lim** [comment]
시간표는 요일 별로 하나 등록 가능한 것으로 했었는데, 그 시간 내에서 다시 뛰는 것은 얘기 안하긴 했었습니다..
저도 그냥 한번만 뛰고 다시 못누르는 것으로 생각하긴 했는데,, 괜찮을 지 애매하네요 😢

**Comment by shortboy7** [comment]
시간표 저장할 때도 요일 하나 당 하나의 시간표만 저장되게 바꾸는 게 좋을 거 같고, 다시 생각해보니 위 제한을 설정하면 한번 뛸 때 실수로 일시정지 대신 종료 눌러버리면 그 날은 아예 기록이 안되는 불상사가 일어날 거 같긴하네요.

**Comment by Yeonji-Lim** [comment]
설정한 시간 안에 달린 기록 모두를 긁어오는 거는 힘들까요?

**Comment by dasomahn** [comment]
> 설정한 시간 안에 달린 기록 모두를 긁어오는 거는 힘들까요?

서버에서는 큰 문제 없는데, 
기획 추가해야되는거랑 그걸 적용할 프론트가 조금 걱정입니다

지금은 캘린더에서 날짜를 선택하면 바로 해당 기록으로 넘어가는 거로 알고 있어서,
시간으로 검색하는 조건을 추가하면 시간 설정 폼을 또 따로 기획 & 추가 구현해야 될거구
검색 설정은 유지한채 날짜에 기록이 두개 이상이 된다고 가정하면

날짜별 조회 방법 (두개 이상 기록)
- 그냥 나란히 위아래로 나열 (스크롤 생길 가능성 ↑)
- depth 하나 더 추가
    - 날짜 선택 -> 날짜에서 원하는 기록 선택(기획 필요) -> 기록 세부 조회
- 아코디언 형식
    - 날짜 선택 -> 날짜에서 원하는 기록 선택(기획 필요) -> 세부 기록 펼쳐지게, 재클릭 시 닫히기
    - 프론트 구현 난이도 ↑ 예상 됩니다 .....
- 등등.....

**Comment by dasomahn** [comment]
제가 생각했을 때는 시간표 내에 한번만 뛸 수 있게 제한해서
시간표 하루에 한번(유지) - 기록 시간표 내 한번(제한 추가) => 하루에 한번만 기록
을 하는게 제일 깔끔할 것 같긴 합니다...

> 실수로 일시정지 대신 종료 눌러버리면 그 날은 아예 기록이 안되는 불상사가 일어날 거 같긴하네요.
저도 이게 약간 걱정인데, 종료 누를 때 "종료하면 다시는 뛸 수 없습니다. 설정한 시간표 내에 또 뛰고 싶으면 일시정지 기능을 활용해주세요. 달리기를 완전히 종료하려면 확인을 눌러주세요" 식의 알림을 띄워 최대한 방지하는게 어떨까요?

> 시연할 때 한번 밖에 못보여 주지 않나요...?
흠 이거는... 사람들마다 가입하라고 해서 각자 해보시라 하기...?

**Comment by Yeonji-Lim** [comment]
흠 그날의 기록들을 두번 뛰면 두번으로 나눠 보여주지 말고 한번에 합쳐서 보여주는거는요?

시간, 거리, 속도 -> 합쳐서 보여주기
좌표 기록 -> 두 리스트를 모두 합쳐서 하나의 리스트로 반환

**Comment by dasomahn** [comment]
그런 거라면 그냥 일별 기록 **요약** API로 바꿔서 구현해달라 하면 될 것 같아요!!

좌표 기록은 [ { 1번기록1, 1번기록2 }, { 2번기록1, ..., 2번기록n} ] 이런 식으로 묶어서 보내면 프론트 지도에서 각각의 루트로 표시해주는건가요?

**Comment by Yeonji-Lim** [comment]
아 맞네요..! 
좌표 기록은 기존과 동일하게 [ { }, { }, .. , { }, { }] 으로 띄워주면 될 거 같아요 프론트 입장에서 받을 때는 그냥 하나의 기록을 받은 거 처럼요!

그리고 일별 기록은 안뜨는데 또 월별 기록에서는 잘 뜬다고 하네요 수정시 참고하시면 될 거 같아요

**Comment by Yeonji-Lim** [comment]
아 근데 지금 일별 기록 요약 API summary 밑에 있는거 다 어떤 날짜를 눌러도 0이 뜨고 있어요

**Comment by dasomahn** [comment]
> 좌표 기록은 기존과 동일하게 [ { }, { }, .. , { }, { }] 으로 띄워주면 될 거 같아요 프론트 입장에서 받을 때는 그냥 하나의 기록을 받은 거 처럼요!

넵! 종료할 경우 location의 status가 end로 따로 들어오나요?! 그게 아니라면 구분지어 보내야할 것 같아요

> 아 근데 지금 일별 기록 요약 API summary 밑에 있는거 다 어떤 날짜를 눌러도 0이 뜨고 있어요

안그래도 이슈 전달 받아서 상황 확인해보고 공유하겠습니다!

**Comment by Yeonji-Lim** [comment]
> 종료할 경우 location의 status가 end로 따로 들어오나요?! 그게 아니라면 구분지어 보내야할 것 같아요

그런데 이부분은 어차피 달리기를 다시 시작하면 record가 하나 더 생기는 거니까 괜찮지 않나요?

그리고 지금 보니까 클럽 21 의 2023-02-02는 되는데 클럽 31은 다 안되고 있어요!

**Comment by dasomahn** [comment]
> 그런데 이부분은 어차피 달리기를 다시 시작하면 record가 하나 더 생기는 거니까 괜찮지 않나요?

지도 표시할 때 구분이 없으면 기록 여러개가 싹다 연결될까봐요...! 일단 합쳐서 보내고, 프론트측에서 문제있다 하면 나중에 분리시키든 하겠습니당

> 그리고 지금 보니까 클럽 21 의 2023-02-02는 되는데 클럽 31은 다 안되고 있어요!

감사합니다! 확인해볼게용

**Comment by dasomahn** [comment]
하루에 한번 제한하는거로 하고 이슈 닫겠습니다!
