### ISSUE TITLE
배포된 서버에서 달리기 시작시 해당하는 시간표가 없어 달리기를 시작할 수 없다고 합니다.

### ISSUE THREAD

**Issue by Yeonji-Lim** [Relay-UMC23/relay-server#95]
실제로 해당 시간표가 있는데도 불구하고 달리기를 시작할 수 없다고 떠요
로컬 main에서는 정상 동작하는 것으로 보아 배포에 문제가 있는 것 같아요

**Comment by dasomahn** [comment]
인스턴스 타임존을 한국 시간으로 변경하여 이슈 해결했습니다!

**Comment by Yeonji-Lim** [comment]
해결 확인하여 이슈 닫습니다
