### ISSUE TITLE
데일리 기록 조회 시 목표 종류, 목표값 반환 질문입니다.

### ISSUE THREAD

**Issue by dasomahn** [Relay-UMC23/relay-server#97]
#94 랑 연결되는 질문으로, 너무 길어서 따로 분리합니다!

기존 데일리 기록 조회 시에는 기록 하나를 보여주어, 해당 목표 종류랑 목표치 반환이 가능했습니다.
그러나 기록 여러개를 요약해서 보여주는 방식으로 수정을 한다면, 이 두개 부분에 대해 문제가 생깁니다!
어떻게 처리하는게 좋을까요? 😢

->
기존 방식으로 데일리 조회는 한 기록에 대해서 보여주는 거로 유지하고,
달릴때 이미 기록이 있는지 확인 + 데일리 조회 시 두개 이상이면 에러처리 추가하겠습니다!

**Comment by shortboy7** [comment]
특정 날의 기록을 조회할 때, 그날에 시간표 정보에 있는 목표 종류랑 목표치를 가져오고, 실제로 달린 기록을 가져올 때는 그 날에 있는 running record의 정보들을 합쳐서 
(거리, 시간은 합치고, 속도는 평균을 내서) 보여주면 되지 않을 까요?

**Comment by dasomahn** [comment]
앗 그렇네요! 어차피 하루당 시간표는 하나니까, 목표 정보는 동일하겠군요 좋은 지적 감사합니다 👍🏻

근데 그러면 저희 목표 달성 여부는 첫번째 종료한 기록으로 판단하고 끝인거죠? 한번 종료하면 그 뒤에 얼마를 더 뛰든 첫번째에서 성공/실패한거로 쭉 변경없이 ...?!

**Comment by Yeonji-Lim** [comment]
지금 저희 그 성공 여부를 달리기 종료 시에 판단하죠?

일단은 그렇게 하는게 맞겠네요 😅

**Comment by dasomahn** [comment]
> 지금 저희 그 성공 여부를 달리기 종료 시에 판단하죠?

아 종료시에만 판단하면 마지막 기록으로 판단되겠네요! 우선 위처럼 진행하겠습니당

**Comment by shortboy7** [comment]
GUI 상으로는 달리기 도중에 일정 목표치를 넘으면 색이 바뀌는 식의 기능이 있는 거 같은데, 이러면 성공 여부는 달리기 종료 시점이 아니라 달리는 도중에 판단하는 식일 거 같아요.

**Comment by Yeonji-Lim** [comment]
이 부분은 일단 하루에 한번만 기록되는 것으로 하고 저희가 시연 당일에 기록을 계속 지워주는 것으로 합니다.

**Comment by Yeonji-Lim** [comment]
기록 예외 처리 : 하루에 한번만 기록
record안에 goal, goalType 넣기

이 두가지 이 이슈에서 해결해주세요~~
