### ISSUE TITLE
그룹 삭제시 관련된 memberStatus의 applyStatus의 값을 바꿔주세요

### ISSUE THREAD

**Issue by Yeonji-Lim** [Relay-UMC23/relay-server#99]
그룹 삭제시 club status의 값만 바꿔지는데, 관련 memberstatus도 상태값이 바뀌어야 합니다.

**Comment by shortboy7** [comment]
mysql trigger로 삭제할 때 memberStatus 상태값이 바뀌도록 하는건 어떤가요

**Comment by shortboy7** [comment]
DELIMITER $$
    CREATE TRIGGER after_club_delete
    AFTER UPDATE ON club FOR EACH ROW
    BEGIN
        IF NEW.status = 'inactive' AND OLD.status = 'active' THEN
            UPDATE member_status SET status = 'inactive'
            WHERE club_idx = new.club_idx;
        END IF;
    END;$$
DELIMITER ;

요거 데이터 그립의 콘솔에 입력하면 트리거 적용되어서 club이 inactive로 바뀔 때 그와 관련된 멤버들 상태를 inactive로 바꿔줍니다.

**Comment by dasomahn** [comment]
빠르게 적용하기 좋을 것 같은데요 ??!

> UPDATE member_status SET status = 'inactive'

근데 이 부분은 `UPDATE member_status SET apply_status = 'DELETED'` 이런 식으로 해 할 것 같아요!

**Comment by shortboy7** [comment]
삭제된 memberStatus를 참조하는 timetable들은 아예 삭제되고, running record들은 기록 자체도 삭제되지 않고, status도 변경 안되는거 맞죠??

**Comment by dasomahn** [comment]
> 삭제된 memberStatus를 참조하는 timetable들은 아예 삭제

타임테이블 조회할 때 memberStatus = accepted 인거만 따져서 갖고오는걸로 알고있어서 이거까진 안해도 될 것 같은데, 아싸리 없애는게 나으려나요?
그 뒤는 넵 삭제나 변경 안시키고 냅둬야할 것 같아요! 그룹 없어져도 기록은 보고싶을 수 있으니까요

**Comment by dasomahn** [comment]
> applyStatus, status 모두 변경

status는 변경 안하고 active로 유지되어야 합니당!!  그룹에 참여했었던 기록 자체를 삭제했을때 변경되는건데 아직은 기획에 없는걸로 알고있어서 applystatus만 변경해주는걸로 햐주심 될 것 같아요!

**Comment by Yeonji-Lim** [comment]
applystatuts에서 delete로 표기합시당
트리거 위에 올려준거대로 제가 이미 만들어버렷어가지고 삭제할게요

**Comment by shortboy7** [comment]
```
DROP trigger if exists after_club_delete;

DELIMITER $$
    CREATE TRIGGER after_club_delete
    AFTER UPDATE ON club FOR EACH ROW
    BEGIN
        DECLARE endOfRow BOOLEAN DEFAULT FALSE;
        DECLARE m_idx BIGINT;
        DECLARE memberCursor CURSOR FOR
            SELECT member_status_idx
            FROM member_status
            WHERE member_status.club_idx = OLD.club_idx;
        DECLARE CONTINUE HANDLER FOR NOT FOUND SET endOfRow = TRUE;

        IF NEW.status = 'inactive' AND OLD.status = 'active' THEN
            UPDATE member_status SET apply_status = 'DELETED'
            WHERE club_idx = new.club_idx;

            OPEN memberCursor;

            updateLoop : LOOP
                FETCH memberCursor INTO m_idx;
                DELETE FROM time_table WHERE member_status_idx = m_idx;
                IF endOfRow THEN
                    LEAVE updateLoop;
                END IF;
            END LOOP updateLoop;

            CLOSE memberCursor;
        END IF;

    END;$$
DELIMITER ;
```
요렇게 할까요

**Comment by Yeonji-Lim** [comment]
이슈 해결되어 닫겠습니다~
